server:
  port: 8888
 
spring:
  datasource:
    username: root
    password: 121982
    url: jdbc:mysql://localhost:3306/life?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: html5
    servlet:
      content-type: text/html
 
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.echoBuzzing.model
 
#showSql
logging:
  level:
    com:
      example:
        mapper : debug